#!/bin/bash

## BOILERPLATE
source $(dirname $0)/_ci-common

## ENVIRONMENT

## Some knobs to parameterize environment modules:
### DEV_CI_PRGENV    - one of cray, intel, gnu
### DEV_CI_CRAYPE    - one of haswell, mic-knl
### DEV_CI_COMPILER  - module/version (empty version for default)

DEV_CI_PRGENV=${DEV_CI_PRGENV:-cray}
for x in intel gnu cray; do module swap PrgEnv-$x PrgEnv-${DEV_CI_PRGENV} ; done 2>/dev/null

DEV_CI_CRAYPE=${DEV_CI_CRAYPE:-haswell}
for x in haswell mic-knl; do module swap craype-$x craype-${DEV_CI_CRAYPE} ; done 2>/dev/null

DEV_CI_COMPILER=${DEV_CI_COMPILER:-$(module -t avail cce/ |& sort -rV | grep -v classic | grep -m1 ^cce)}
[[ -n ${DEV_CI_COMPILER} ]] && module swap ${DEV_CI_COMPILER%/*} ${DEV_CI_COMPILER}

export TMPDIR=/run/user/$(id -u)
export UPCXX_HAVE_OPENMP=1

export NETWORKS="${CI_NETWORKS:-aries}"
export GMAKE="${CI_MAKE:-${GMAKE:-make}}"
MAKE_CMD="$GMAKE ${CI_MAKE_PARALLEL:--j8}"

## CONFIGURE
if [[ $STAGES =~ ,configure, ]]; then
  $UPCXX/configure ${GASNET:+ --with-gasnet=$GASNET}
fi

## BUILD
if [[ $STAGES =~ ,build, ]]; then
  eval $DO_BUILD
fi

## TESTS
if [[ $STAGES =~ ,tests, ]]; then
  eval $DO_COMPILE || touch .pipe-fail
fi

## RUN
if [[ $STAGES =~ ,run, ]]; then
  unset TMPDIR
  time salloc -C ${DEV_CI_CRAYPE##*-} -t 120 -q interactive -N 2 -- time $GMAKE ${MAYBE_DEV}run-tests || touch .pipe-fail
fi

## DONE
finished
