#!/bin/bash

## BOILERPLATE
source $(dirname $0)/_ci-common

## ENVIRONMENT
module purge
module load $(module -t avail pgi/ 2>&1 | grep ^pgi/ | sort -V | tail -1)
module load pgi-cxx14
module load spectrum-mpi
module load lsf-tools
module load cuda
export GASNET_IBV_PORTS=mlx5_0+mlx5_1
export UPCXX_HAVE_OPENMP=1
export TMPDIR=${XDG_RUNTIME_DIR:-/tmp}

export NETWORKS="${CI_NETWORKS:-ibv}"
export GMAKE="${CI_MAKE:-${GMAKE:-make}}"
MAKE_CMD="$GMAKE ${CI_MAKE_PARALLEL:--j8}"

# Issue #334
export TEST_EXCLUDE_ALL=test/future.cpp

## CONFIGURE
if [[ $STAGES =~ ,configure, ]]; then
  $UPCXX/configure ${GASNET:+ --with-gasnet=$GASNET} \
	CC=pgcc CXX=mpicxx MPIRUN_CMD="jsrun -g 1 -p %N %C" \
        --enable-ibv-multirail --with-ibv-max-hcas=4  --with-ibv-physmem-max=2/3 \
        --enable-ibv-odp --with-cuda
fi

## BUILD
if [[ $STAGES =~ ,build, ]]; then
  eval $DO_BUILD
fi

## TESTS
if [[ $STAGES =~ ,tests, ]]; then
  eval $DO_COMPILE || touch .pipe-fail
fi

## RUN
if [[ $STAGES =~ ,run, ]]; then
  unset TMPDIR
  time bsub -W 30 -nnodes 4 -P csc296 -I "time $GMAKE ${MAYBE_DEV}run-tests NETWORKS='$NETWORKS' || touch .pipe-fail"
fi

## DONE
finished
